services:

  web:
    build:
      context: .
      dockerfile: ./.docker/nginx/Dockerfile
      target: dev
    ports:
      - "127.0.0.1:80:80"
    environment:
      TZ: ${TZ}
      SERVER_NAME: localhost
      PHP_HOST: app
    volumes:
      - ./src/public:/var/www/src/public

  app:
    build:
      context: .
      dockerfile: ./.docker/php/Dockerfile
      target: dev
    environment:
      TZ: ${TZ}
    working_dir: /var/www/src
    volumes:
      - ./src:/var/www/src
