services:

  web:
    image: multi-build-prod-web
    build:
      context: .
      dockerfile: ./.docker/nginx/Dockerfile
      target: prod
    init: true
    ports:
      - "127.0.0.1:80:80"
    environment:
      TZ: ${TZ}
      SERVER_NAME: localhost
      PHP_HOST: app

  app:
    image: multi-build-prod-app
    build:
      context: .
      dockerfile: ./.docker/php/Dockerfile
      target: prod
    environment:
      TZ: ${TZ}
